### ISSUE TITLE
Warnings: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by r0max** [jrgp/linfo#100]
When accessing linfo, two warnings are spilled out:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/http/linfo/src/Linfo/OS/Linux.php on line 1034

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/http/linfo/src/Linfo/OS/Linux.php on line 1351

The fix is simply to delete the "continue" from the switch-case.

UPDATE: considering the logic, it makes more sense to break out to the upper switch.

```bash
diff --git a/src/Linfo/OS/Linux.php b/src/Linfo/OS/Linux.php
index d77ef91..66a6447 100644
--- a/src/Linfo/OS/Linux.php
+++ b/src/Linfo/OS/Linux.php
@@ -1031,7 +1031,7 @@ class Linux extends Unixcommon
                     $charge_now = Common::getIntFromFile($b.'/charge_now');
                     break;
                 default:
-                    continue;
+                    continue 2;
                     break;
             }
 
@@ -1348,7 +1348,7 @@ class Linux extends Unixcommon
                                 $state = 'Up (Stopped)';
                             break;
                             default:
-                                continue;
+                                continue 3;
                             break;
                         }
                     break;
```

**Comment by jrgp** [comment]
Hey, thanks for pointing this out. Will follow up

**Comment by skoch872** [comment]
Hello, is there already information when the release is ready?

Thanks!
