### ISSUE TITLE
PHP8 TypeError 

### ISSUE THREAD

**Issue by ilianiv** [jrgp/linfo#117]
> In PHP 8, internal function parameters have types and value validations enforced, and will throw \TypeError or \ValueError exceptions if the expected type or value is not allowed.

**Error:**
ceil(): Argument #1 ($num) must be of type int|float, string given

**At:**
.../vendor/linfo/linfo/src/Linfo/OS/Linux.php::getUptime()

```
 // Seconds
 list($seconds) = explode(' ', $contents, 1);

 // Get it textual, as in days/minutes/hours/etc
 $uptime = Common::secondsConvert(ceil($seconds));
                                  ^^^
```

**Comment by jrgp** [comment]
Thanks for the fix. I wonder if there are any other old bugs lurking..

**Comment by ilianiv** [comment]
Hi @jrgp,
Please release a new version with this fix. 
linfo is still incompatible with PHP 8 due to this bug.

**Comment by jrgp** [comment]
Hey, just released v4.0.6

**Comment by ilianiv** [comment]
@jrgp maybe you've forgot to publish v4.0.6 in packagaist https://packagist.org/packages/linfo/linfo?
4.0.5 it the latest there.

**Comment by jrgp** [comment]
Ah yeah that isn't done automatically yet. Will look into it.

**Comment by jrgp** [comment]
v4.0.6 has been published
