### ISSUE TITLE
php 8.1 support

### ISSUE THREAD

**Issue by icyz** [jrgp/linfo#125]
hello, I'm trying to use Linfo on PHP 8.1 but there are some problems: the @-operator doesn't work anymore.

thanks, for that cool project! :-)

**Comment by jrgp** [comment]
Thanks for letting me know! Glad you like the project

**Comment by jrgp** [comment]
I just verified that linfo works out of the box on php 8.1.6 on Fedora 36 (with selinux off). 

Can you please paste me the errors you're seeing?

**Comment by icyz** [comment]
`Warning: disk_total_space(): Permission denied in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 682 (error level: 2)
Warning: disk_free_space(): Permission denied in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 683 (error level: 2)
Warning: disk_total_space(): Permission denied in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 682 (error level: 2)
Warning: disk_free_space(): Permission denied in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 683 (error level: 2)
Warning: disk_total_space(): No such file or directory in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 682 (error level: 2)
Warning: disk_free_space(): No such file or directory in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 683 (error level: 2)
Warning: disk_total_space(): Permission denied in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 682 (error level: 2)
Warning: disk_free_space(): Permission denied in /var/www/zerogestionale/trunk/zero/public/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 683 (error level: 2)`


in `Linux.php` :
`$size = @disk_total_space($mount[2]);`
`$free = @disk_free_space($mount[2]);`

now the @-operator does not suppress errors anymore. 

thanks!

**Comment by jrgp** [comment]
I just committed a check which should avoid those errors. Please confirm.

**Comment by icyz** [comment]
Yes, mate! 
I checked and it works like a charm :-)

**Comment by icyz** [comment]
did you plan to create a new release? I'm asking for people (like me) using composer :-)
thanks mate!

**Comment by jrgp** [comment]
Released! https://github.com/jrgp/linfo/releases/tag/v4.0.7
