### ISSUE TITLE
No drives shown on FreeBSD 12.4

### ISSUE THREAD

**Issue by hbokh** [jrgp/linfo#127]
Hello,

The issue I'm having is that the (HTML) output shows "Drives - None Found", but it should show a "Samsung 840 EVO 120GB".
FWIW this is in file ` /var/run/dmesg.boot`:

```console
$ grep ^ad /var/run/dmesg.boot
ada0 at ahcich0 bus 0 scbus0 target 0 lun 0
ada0: <Samsung SSD 840 EVO 120GB EXT0BB6Q> ACS-2 ATA SATA 3.x device
ada0: Serial Number S1D5SOMETHING
ada0: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 512bytes)
ada0: Command Queueing enabled
ada0: 114473MB (234441648 512 byte sectors)
ada0: quirks=0x3<4K,NCQ_TRIM_BROKEN>
```

FreeBSD version: 12.4-RELEASE (but this issue occurred on 12.3 and 11.x too).
PHP version: 8.1.13
Linfo version: latest Git

**Comment by jrgp** [comment]
Thanks for the report!
