### ISSUE TITLE
php 8.2 Deprecated: Creation of dynamic property 

### ISSUE THREAD

**Issue by icyz** [jrgp/linfo#128]
Hello, I found this:

`Deprecated: Creation of dynamic property Linfo\Parsers\Hwpci::$exec is deprecated in .../public/vendor/linfo/linfo/src/Linfo/Parsers/Hwpci.php on line 60 (error level: 8192)`

thanks

**Comment by jrgp** [comment]
Thanks! 

Feel free to open more PRs/issues for other broken things you find too.
