### ISSUE TITLE
wrong CPU-Load under Windows Multi-Core

### ISSUE THREAD

**Issue by Gummibeer** [jrgp/linfo#14]
I watched the results from Linfo and from the Windows-Ressourcemonitor a while and there are great differences between them.

The Linfo Result is just the first Core (it's an 8 Core Intel) this Core is permanent between 50-70% - this is the Linfo result. But the whole CPU-Load in average is 30-40%. With an 8 times 3.7 GHz this is great difference and my live tracker for system health is nearly useless with these differences.

Would be nice if you can fix this and get the load for every Core in the CPU Array and the average load over all cores in the Load String.

**Comment by Gummibeer** [comment]
Ok, I debuged a bit and the error is in the result from the COM Class itself. It just returns 1 integer and not 8 like the documentation says.
I will look around to find a solution.

**Comment by jrgp** [comment]
Thanks for looking into this. Also it might help if you look at the source to the COM module to see how it works. 

I can't really speak for windows as I don't know much about it but on Unix, determining cpu load is an extremely complex operation comprised of adding together/averaging a bunch of values within a few seconds; it wouldn't surprise me of doing it properly on windows was as arduous. Look at the cpu usage method in the Linux os class to see what I mean.

**Comment by Gummibeer** [comment]
The function for windows looks right but the error is that the result from the COM-Query is an Array with one single child. The for each just runs once and that's why it's the wrong (just the first core) result.

I looked into the COM-Class docu and the docu tells it a bit hidden:

> **LoadPercentage**
> Data type: uint16
> Access type: Read-only
> Qualifiers: Units (Percent)
> Load capacity of each processor, averaged to the last second. Processor loading refers to the total computing burden for each processor at one time. This property is inherited from CIM_Processor.

https://msdn.microsoft.com/en-us/library/aa394373(v=vs.85).aspx

It's just the load average _for each processor_ not for each core. But it's bad that the average over the last minute from one CPU is just the first core and not the average from all cores of one CPU over the last minute.

I will look around to find another method that will work properly. But the first looks just resolved into the exec/system functions - and you don't want to use these functions if I read it right!?

One possibility could be to use an extra setting for precise CPU-Load that is combined with the exec/System functionality.

**Comment by Gummibeer** [comment]
Ok, it's the *** windows *** they have to localize every command ... so the system cmd command should be:
german: ```typeperf -sc 1 "\Prozessor(_Total)\Prozessorzeit (%)"````
english: ```typeperf -sc 1 "\processor(_total)\% processor time"````

don't tested it with php system() but i don't think that you haven't to localize this command in php. so the system language is important and it would be a pain to write this switch case ...
I will try to implement it in my code and test it over time.

**Comment by jrgp** [comment]
That language thing seems like a horrible pain in the ass. With regards to calling external programs: if there isn't any other way of doing it, try to do it in the same way that the BSD and SUN classes do it.

**Comment by Gummibeer** [comment]
This is my function to test this command:

```php
function getCpuLoad()
    {
        $cmd = '\Prozessor(_Total)\Prozessorzeit (%)';
        exec('typeperf -sc 1 "'.$cmd.'"', $out);
        $out = array_filter($out);
        $line = false;
        foreach($out as $key => $value) {
            if(stripos($value, $cmd) !== false) {
                unset($out[$key]);
            } elseif(stripos($value, '"') === 0) {
                $line = $value;
            }
        }
        preg_match("/\".*\",\"(.*)\"/", $line, $out);
        $load = number_format($out[1] * 1, 2) * 1;

        return $load;
    }
```

without any language settings yet. It works for me but without the help of the users they wan't this precise functionality this won't work for this class. The way I process the output is horrible but it works and just have to do it's job for the moment.

**Comment by jrgp** [comment]
It's damn depressing that they use language specific names per each key. Does the value always look unique-ish such that you could just regex match it? I don't have a windows installation available for me to readily test this.

Also please use the CallExt class rather than raw exec() as I prefer to have the external command executions abstracted away (if you intend on making a merge request/etc)

**Comment by Gummibeer** [comment]
Yeah, the output is always the same. Ok, I will have a look for this class - I combine these functions and will test it for german - english should work cause this was my start language. But I can't implement other languages.

I will post the result of my work here cause I just loaded your library with composer.

**Comment by Gummibeer** [comment]
```php
public function getLoad() {

    // Time?
    if (!empty($this->settings['timer']))
        $t = new LinfoTimerStart('Load Averages');

    if($this->settings['precise_cpu']) {
        switch($this->settings['language']):
            case 'de':
                $cmd = '\Prozessor(_Total)\Prozessorzeit (%)';
                break;
            default:
                $cmd = '\processor(_total)\% processor time';
                break;
        endswitch;

        exec('typeperf -sc 1 "'.$cmd.'"', $out);
        $out = array_filter($out);
        foreach($out as $key => $value) {
            if(stripos($value, $cmd) !== false) {
                unset($out[$key]);
            } elseif(stripos($value, '"') === 0) {
                preg_match("/\".*\",\"(.*)\"/", $value, $out);
            }
        }

        return round($out[1] * 1, 2) . "%";
    } else {
        $load = array();
        foreach ($this->wmi->ExecQuery("SELECT LoadPercentage FROM Win32_Processor") as $cpu) {
            $load[] = $cpu->LoadPercentage;
        }
        return round(array_sum($load) / count($load), 2) . "%";
    }
}
```

I'm sorry but with your CallExt class I got an error from ```throw new CallExtException('Exec `'.$name.'\' not found');``` cause I don't know witch path I have to set. If you find it out you can replace it.
The setting have to paste into your default settings file ```$settings['precise_cpu'] = false;``` you can rename it if you want it in any array or wan't a better name.

I hope that this would help you!?

**Comment by jrgp** [comment]
CallExt probably isn't as appropriate here as it is on unix. That code snippet does seem pretty helpful. It'd incorporate it almost verbatim once we find a way around the language thing, which bothers me, as Linfo is supposed to just work out of the box no questions asked and not everyone uses en/de

**Comment by Gummibeer** [comment]
One possibility to detect it automaticly scould be the ```HTTP_ACCEPT_LANGUAGE``` (my result: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4) but I don't know how reliable this is. I will search more for a solution without a user setting.

**Comment by jrgp** [comment]
I think that http header is the preferred language of the clients web browser and that might not match that of the windows server. 

That reg command may work but do we really want a php script directly reading the php registry? Lol 

I'm convinced there's a language agnostic way of getting the key but because it's windows I'm sure finding out how will be arduous.

**Comment by Gummibeer** [comment]
Yeah, all these solutions aren't good solutions - just the first I found.^^

And yeah, getting systeminformations from windows without going into the system itself isn't easy. I'm wondering why the ```sys_getloadavg()``` won't work under windows.

**Comment by Gummibeer** [comment]
The good thing for security: in none of these exec commands and things like this we will use variable user input - just fixed commands. So the abuse chance is nearly zero - and with the COM class activated the library isn't shared host compatible (if the shared host runs windows).

**Comment by jrgp** [comment]
Regarding fixed commands: exactly. The reason why I consider linfo in general secure is that it doesn't take in user input at all. 

I just looked at the php.net page for sys_getloadavg, it says it isn't implemented under Windows. Probably because there isn't a meaningful equivalent value to unix's system load.
