### ISSUE TITLE
Output line from /proc/stat as a solution to sleep()

### ISSUE THREAD

**Issue by Keeo** [jrgp/linfo#15]
I was thinking about realtime cpu usage in percents and I think that Linfo should provide pure values from `/proc/stat` instead of trying to make percents.

Linfo is fast, designed to be called once per second. So why don't move responsibility of making cpu usage in percentage to program that uses it? That program would have already values from last call so it would not need to wait. Moreover library sleeps one sec so when mentioned program is not synced then there will be gaps in results.

Since I didn't see configuration for this anywhere, I suspected that it's not possible, and hence writing issue.

Hackish solution is to change loop count to one and this function:
```php
private function cpuPercent($key, $line) {
    return $line;
}
```

**Comment by jrgp** [comment]
Pull request please.

**Comment by Fro99666** [comment]
i've checked, the sleep is set to 1 millisec, and it has to be set to have /proc stat refreshed (each milli sec) to get cpu %.
i didn't found another way to get cpu % with pure php, there s solution using exec command, but i dunno if it will do a gain or loss of performances.
The posted solution, will draw numbers that can't be undertood by users.
