### ISSUE TITLE
Nice 500 error after updating linfo 

### ISSUE THREAD

**Issue by kamijoutouma** [jrgp/linfo#18]
```2015/08/31 14:35:32 [error] 17565#0: *116779 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Can't use function return value in write context in /home/touma/webserver/linfo/lib/class.OS_Linux.php on line 1513" while reading response header from upstream, client: ::ffff:0.0.0.0, server: stats.ilp.moe, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "stats.ilp.moe"```

**Comment by jrgp** [comment]
This happened to me today too, on an older version of PHP. I'll make a fix commit soon.

**Comment by jrgp** [comment]
Should be fixed. Do a ```git pull``` and you should be golden.

**Comment by kamijoutouma** [comment]
thank you +1
