### ISSUE TITLE
Output without echo

### ISSUE THREAD

**Issue by Gummibeer** [jrgp/linfo#19]
It would be really nice if you can add an output type that returns a php array and not echo everything. I would implement this in a Laravel5 package and found a workaround to get the data in php but it's not the nice way.
It would be better if I can call something like:

```php
require_once __DIR__.'/init.php';
try {
    $linfo = new Linfo;
    $linfo->scan();
    $data = $linfo->output('php');
    // do something with the php array
    // save in database, create graphics/charts, send email to admin and so on
} catch (LinfoFatalException $e) {
    // handle the Exception
}
```

**Comment by jrgp** [comment]
I think $linfo->getInfo() does what you want.

**Comment by jrgp** [comment]
I just tried and this does what you'd expect. You can just use the getInfo() method as it returns the php array.

```php
require_once __DIR__.'/init.php';

try {
        $linfo = new Linfo;
        $linfo->scan();
        var_dump($linfo->getInfo());
}

catch (LinfoFatalException $e) {
        echo $e->getMessage()."\n";
        exit(1);
}

```

```
# php index.php | head
array(30) {
  ["OS"]=>
  string(5) "Linux"
  ["Kernel"]=>
  string(17) "3.13.0-45-generic"
  ["AccessedIP"]=>
  string(7) "Unknown"
  ["Distro"]=>
  array(2) {
    ["name"]=>
```

**Comment by Gummibeer** [comment]
Ok, thx :smile:

**Comment by Gummibeer** [comment]
Ok, I got another problem with your package's structure and requirements.

1) It's not fine that I have to load the init.php myself if I load your package via composer.
2) There have to be a functionality to pass the settings in the constructor - cause it's not, normal way, possible to create a file in the vendor folder (composer).

the first can get solved via:
```
"files": [
            "vendor/linfo/linfo/init.php"
        ]
```
and ```define('LINFO_CLI', true);```

But for the second one the package have to get changed :disappointed:

**Comment by jrgp** [comment]
Yeah this work needs to be done. I'm open to a pull request if you feel up to the challenge.

**Comment by Gummibeer** [comment]
it's done:  #20

**Comment by jrgp** [comment]
If you have time, would you be able to edit the readme to include a section on how to use Linfo as a library in composer ?

**Comment by jrgp** [comment]
@Gummibeer actually I think it'd be better if you would be able to add the "files" array you mentioned earlier to composer.json :)

**Comment by Gummibeer** [comment]
You mean in your composer.json?
In mine it is ;D

**Comment by Gummibeer** [comment]
#21
