### ISSUE TITLE
Clean package

### ISSUE THREAD

**Issue by Gummibeer** [jrgp/linfo#23]
It would be good to clean this package to it's base - just PHP classes and bring them in a namespace. This supports the development of projects that extend this package and works better with composer (autoload PSR).
The usage examples can get an own repo (linfo/usage what ever).
The namespace also reduces possible conflicts with other classes.

This will be a great change that includes much of refactoring, renaming, moving and so on.

Suggested for 2.1 or even 3.0 cause this will be a big change that totaly changes the way this package is used/called.

**Comment by jrgp** [comment]
I completely agree. Migrating Linfo to use PHP namespaces and properly adhere to PSR standards is something I've known needs to happen for a while but I've been putting it off. These definitely would warrant a 3.0 release.

The thing that concerns me is that

**Comment by Gummibeer** [comment]
That!?^^

**Comment by jrgp** [comment]
Meant to say (before i got distracted) dropping support for php installed from the repos that come with rhel5 and rhel6 as I think they're extremely old. But most of the installs of Linfo I see from google are on debian and ubuntu so that probably doesnt matter as much.

**Comment by Gummibeer** [comment]
The Support isn't really droped cause the older systems can use older versions.
But namespaces and psr is nearly required with composer and I think that it is A bit more important to secure the possibility to include this package in Backend Software as a data deliverer/source and not just a data display.

**Comment by jrgp** [comment]
Those are good points and I agree. I'm going to be pushing a namespaced version of Linfo to a feature branch by tomorrow and we can work on it and get it ready to be merged to master.

**Comment by jrgp** [comment]
Namespaced Linfo: https://github.com/jrgp/linfo/tree/namespaces

Looking forward to your feedback :)

**Comment by Gummibeer** [comment]
First thing that I struggled is the missing composer autoloader:
https://getcomposer.org/doc/04-schema.md#psr-4
This will replace your `spl_autoload_register()` function and opens the world for every developer that uses composer.

The next thing: with composer it's recommended to wrap your package code into a _src_ folder to make it simpler adding the PSR-4 autoload.

You have also 3 files in the root folder that don't belongs to the package directly, just to your development, or are unnecessary:
- .gitattributes
- .travis.yml
- Linfo.sublime-project

Except of these things it looks very good and much cleaner. :)

**Comment by jrgp** [comment]
I just got psr-4 reload to work (tested it myself) and removed the sublime project file. I don't know where to put the gitttributes and the travis file for them to still work.

Let me know how I can make stuff better from here :)

**Comment by jrgp** [comment]
Also just released v2.0.3 from master, the last of the v2.x series of Linfo. The new namespaces branch will become v3.x

**Comment by jrgp** [comment]
I tweaked a ton of things and added a new README.md, this time with a screenshot :) 

https://github.com/jrgp/linfo/tree/namespaces xD

**Comment by Gummibeer** [comment]
If you need these teo files in Git and not just localy then it's ok. For me they look "useless".
The PSR4 looks good and the readme is also fine! :)

I had no time today so I will check this later and build the first Version of the laravel package with 2.0.3 and after that I can Start to test and implement the v3.

Just for you: you can create v3.0.0-dev/alpha/beta to let other use these with composer.
https://getcomposer.org/doc/04-schema.md#version

**Comment by jrgp** [comment]
The travis.yml controls automated unit tests which run as post commit hooks. The gitattributes makes when you make a tagged release, the resulting tarball gives the version in the lower right corner rather than "git"

**Comment by Gummibeer** [comment]
I have created the first version of the laravel wrapper (without your namespaces) and start at dev branch to include your namespaced branch - it works everything well. :)
If you are ready you can create the version 3.0.0 and then I will realese the next version and after that I can create new features for the package - including some laravel stuff (artisan command(s), a view for the results and so on)

**Comment by jrgp** [comment]
There are still one or two things I need to finish up with the namespaces branch before I release it. Hopefully I'll be able to do that in 12 hours or so.

**Comment by jrgp** [comment]
Took care of a bunch of stuff just now:
- Fixed ncurses support and added NCURSES.md
- Updated README file with screenshot of ncurses
- Merged "namespaces" to master and deleted branch

Will be continuing to tweak bugs as I find them and test out Linfo on multiple platforms before I make the 3.x release. Biggest thing is to make sure it works on Windows... I need to fire up a Windows VM now  :expressionless:

**Comment by Gummibeer** [comment]
I have a Windows Root for testing. ;) Say me what you want to test/do and I can run it on a real machine. ;)
And I created a little pull-request for your autoloader #24 
Are there any constants I have to define if I want to use the Linfo-Class directly?

**Comment by Gummibeer** [comment]
I have created the first artisan command for the package to get some infos via artisan - the next one will be a check that compares the loads with the critical values of the config and fires an event if they are reached to let the dev use these events for logging, sending emails or what ever he want to do.

**Comment by jrgp** [comment]
Would you be able to run Linfo on your windows box and provide me with a screenshot? :)

**Comment by Gummibeer** [comment]
Yes I can - simple call the index, or!?

**Comment by jrgp** [comment]
Just go to the index.php file and provide a screenshot of the page it displays :)
