### ISSUE TITLE
.htacess on apache 2.4

### ISSUE THREAD

**Issue by Fro99666** [jrgp/linfo#25]
Hi,

on apache 2.4 i have the following error in apache logs:
/var/www/info/.htaccess: Regex could not be compiled

to solve the trouble i changed  &lt;FilesMatch "\*"&gt; by &lt;FilesMatch ".\*"&gt;, i don't have any apache2.2 to test if the fix work for both

if you can get an eye, thanks !

**Comment by jrgp** [comment]
Can you do a git pull? Latest linfo shouldn't have .htaccess files with that directive.

**Comment by Fro99666** [comment]
yup, false report then, sorry !
