### ISSUE TITLE
Warning: usort() expects parameter 2 to be a valid callback, class 'OS_Windows'

### ISSUE THREAD

**Issue by Beaten-Sect0r** [jrgp/linfo#27]
Warning: usort() expects parameter 2 to be a valid callback, class 'OS_Windows' not found in C:\*\src\Linfo\OS\Windows.php on line 278

Warning: usort() expects parameter 2 to be a valid callback, class 'OS_Windows' not found in C:\*\src\Linfo\OS\Windows.php on line 382

Warning: usort() expects parameter 2 to be a valid callback, class 'OS_Windows' not found in C:\*\src\Linfo\OS\Windows.php on line 422

**Comment by jrgp** [comment]
Do a git pull from master again; I may have fixed this...

**Comment by Beaten-Sect0r** [comment]
Warning: usort() expects parameter 2 to be a valid callback, class 'Windows' not found
Linfo\OS\Windows - so works.

**Comment by jrgp** [comment]
Could you submit a pull request? :3

**Comment by jrgp** [comment]
Thanks a bunch for the fix. One more thing though. Would you be able to provide me with a screenshot of linfo running on Windows ? 

I haven't released a new release post refactor as I don't have anything Windows to test on.

**Comment by Beaten-Sect0r** [comment]
![linfo](https://leto27g.storage.yandex.net/rdisk/19ab73dba422fe00d5545b8098637c7a0244a93c7e275a251a54cb94ba9fcf32/inf/4vchkI1Zulr7caXFgutZTtD0yCpc5Y4UjynfXoiPyOXvoIpsD6EVo4ZIgimhjwIuzd3sMaH7cv-V2RlbXGzg-g==?uid=0&filename=scr_linfo.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=459418e4b7dfce8877d3ac91dad60ddd&force_default=no&ycrid=na-44c359474b944cc317055bb315350c79-downloader2g)
