### ISSUE TITLE
Accessed IP

### ISSUE THREAD

**Issue by SimaWB** [jrgp/linfo#3]
With <b>local server</b> on Windows with IIS (I use 7.5); 
Accessed IP returns Unknown. Because of <b> $_SERVER['SERVER_ADDR']</b> 

So I use 

``` php
gethostbyname($_SERVER['SERVER_NAME']) 
```

instead of 

``` php
$_SERVER['SERVER_ADDR'] 
```

in <b>class.LinfoOutput.php</b> file.

**Comment by kamijoutouma** [comment]
@jrgp just recently noticed when doing `?out=xml` the ip is there it also might be doing the same on other output methods

**Comment by jrgp** [comment]
Run git pull. This should fix it https://github.com/jrgp/linfo/commit/e04a6a826f80b5af1e2a31a529d98145eca7d037
