### ISSUE TITLE
Undefined index: additional_paths on Mac OSX

### ISSUE THREAD

**Issue by cedricve** [jrgp/linfo#30]
I get  
`
exception 'ErrorException' with message 'Undefined index: additional_paths' in /Users/cedricverst/www/web/vendor/linfo/linfo/src/Linfo/Parsers/CallExt.php:67`

Got PCRE installed and using PHP 5.6.10

**Comment by jrgp** [comment]
I'll fix this soon. Are you on the latest git master or a release Tarball ?
