### ISSUE TITLE
OS X memory is reported in Mebibytes

### ISSUE THREAD

**Issue by dbwiddis** [jrgp/linfo#31]
Memory values in OS X are in [Mebibytes](https://en.wikipedia.org/wiki/Mebibyte).

Megabytes are [only used for hard drives](https://support.apple.com/en-us/HT201402).

When calculating swap usage in [Darwin.php](https://github.com/jrgp/linfo/blob/master/src/Linfo/OS/Darwin.php#L408) you're multiplying the returned value by 1 million (Megabyte) rather than the correct 1024<sup>2</sup> (<< 20).
```
            $return['swapTotal'] = $swap_total * 1000000;
            $return['swapFree'] = $swap_free * 1000000;
```

**Comment by jrgp** [comment]
Thanks for the report. Are you able to make a PR with a fix?

**Comment by jrgp** [comment]
Thanks!

**Comment by dbwiddis** [comment]
My pleasure.

I maintain a java-based library providing similar information to yours.  I'll probably visit often to research new ideas. :)
