### ISSUE TITLE
Division by zero in Linux.php line 1651

### ISSUE THREAD

**Issue by TechKat** [jrgp/linfo#36]
I have currently pulled in the dev-master build, as I will only really be using it for my admin panel.

I recently just updated to PHP7. Any recommendations?

**Comment by TechKat** [comment]
Update: I removed Gummibear's Laravel version and used the original copy.

I set `cpu_percent` to false, and that got rid of the problem. This appears to be a `determineCpuUsage` problem?

**Comment by jrgp** [comment]
You're right. I'm not checking if `array_sum($ret)` is > 0, which is what led to this. Can you tell me a little bit about the box you're running Linfo on? Is it a docker container/VM/etc/etc.

**Comment by TechKat** [comment]
I am running Ubuntu 16.04 (xenial), on a VPS managed with VMWare.

**Comment by jrgp** [comment]
Should be fixed per gummibeer's commit.
