### ISSUE TITLE
Show the percentage of drive(s) used

### ISSUE THREAD

**Issue by hitam4450** [jrgp/linfo#38]
Hi, I just installed linfo and I am happy with it. Many thanks for your efforts to provide a solution like linfo to the community.
One feature i am missing is a table showing the percentage of drive(s) capacity used to monitor possible drive lockouts!

regards, hitam4450

**Comment by jrgp** [comment]
Can you confirm what you mean by drive capacity? Linfo currently shows filesystem space usage.
