### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by lrussell887** [jrgp/linfo#4]
Hello,
I've been using Linfo for a while now and it seems to be cluttering my server log with a little error (on every page load):
`2015-01-19 03:40:04: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Notice:  Undefined index: hw in /var/www/default/lib/class.HW_IDS.php on line 281`

I'm using Lighttpd on a Raspberry Pi with FastCGI for PHP.
Thanks!

**Comment by jrgp** [comment]
Will get this fixed within a day or so

**Comment by jrgp** [comment]
@lrussell887 can you please run git pull and see if this commit https://github.com/jrgp/linfo/commit/2dfe45e2753259eb75da46b8e81430b53161a98c fixes it?

**Comment by lrussell887** [comment]
Yep, that seems to have fixed it. Thanks!
