### ISSUE TITLE
PHP library usage

### ISSUE THREAD

**Issue by mitsus** [jrgp/linfo#41]
Hi, 
i followed your guide, so on my debian machine into a subdirectory i've download linfo project. I tested it and all work fine.
Now i created a new directory (outside linfo dir) i launched:

`    
         composer require linfo/linfo
         Do not run Composer as root/super user! See https://getcomposer.org/root for details
         Using version ^3.0 for linfo/linfo
         ./composer.json has been created
         Loading composer repositories with package information
         Updating dependencies (including require-dev)
               - Installing linfo/linfo (v3.0.0)
               Downloading: 100%         

          linfo/linfo suggests installing ext-com (On Windows)
          Writing lock file
          Generating autoload files`

i created a new file api_linfo.php with this values:
<?php
$linfo = new \Linfo\Linfo;
$parser = $linfo->getParser();

var_dump($parser->getCPU());
?>

But when i exec i've this error: PHP Fatal error:  Class 'Linfo\Linfo' not found in

Where are my errors?

Regards

**Comment by Gummibeer** [comment]
Have you included the composer autoloader in your file!?
https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by mitsus** [comment]
Wow @Gummibeer,
thaks a lot now it work fine.

Just last question...where i can find more infos about library? So others command as $parser->getCPU()...for example for take cpu load, memory, ecc?

Thanks a lot

**Comment by Gummibeer** [comment]
Just in the code yet.

**Comment by jrgp** [comment]
Yeah linfo needs docs as well as an interface binding all of the os classes to implement the same methods. Thanks gummibear

**Comment by mitsus** [comment]
Ok sure,
but i don't find for example how to get cpu load % value.

**Comment by mitsus** [comment]
I try to call 
$parser->getCPUUsage()...but it return empty value

**Comment by jrgp** [comment]
Closing this as it's old and I haven't reproduced. Reopen if necessary.
