### ISSUE TITLE
Detect if running in Docker / LXC containers

### ISSUE THREAD

**Issue by Hipska** [jrgp/linfo#46]
I think it would be interesting (just as testing for if running inside VM) to see if Linfo is running inside a container.

**Comment by jrgp** [comment]
It is a good idea and probably really trivial to implement support in the existing Linux OS class. Feel free to submit a patch :)

**Comment by Hipska** [comment]
Yeah, I'm just new to Docker and couldn't find a reliable detection yet. I made the suggestion here, so maybe other have a clue.

**Comment by matriphe** [comment]
I think we can close it? Or we need to solve the LXC part before closing?

**Comment by Hipska** [comment]
Looked at the code and seems fine for me.

**Comment by matriphe** [comment]
@Hipska don't hesitate to try out in Docker container. See if it detects Docker container properly. please use the `master` branch.
