### ISSUE TITLE
Cant get "cpuUsage" with "$linfo->getInfo();"

### ISSUE THREAD

**Issue by noahwaldner** [jrgp/linfo#48]
Cant get the Value of "cpuUsage", its empty.

**Comment by jrgp** [comment]
You need to first call determineCPUPercentage() before running getInfo().
Something like the following should work:

```php
$linfo = new \Linfo\Linfo;
$linfo->getParser()->determineCPUPercentage();
$linfo->getInfo();
```

**Comment by noahwaldner** [comment]
require_once dirname(__FILE__).'/init.php';


$linfo = new Linfo;
$linfo->getParser()->determineCPUPercentage();
$linfo->scan();
$values = $linfo->getInfo();





in $values the CPU Usage Field is empty.

**Comment by jrgp** [comment]
Just looked into this. The following works for me:

```php
<?php

require_once __DIR__ . '/standalone_autoload.php';

$linfo = new \Linfo\Linfo;
$parser = $linfo->getParser();
$parser->determineCPUPercentage();

var_dump($parser->getCPU());
```

And then:

```
$ php foo.php
array(4) {
  [0]=>
  array(4) {
    ["usage_percentage"]=>
    float(5)
    ["Vendor"]=>
    string(12) "GenuineIntel"
    ["Model"]=>
    string(39) "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz"
    ["MHz"]=>
    string(8) "3594.937"
  }
```
