### ISSUE TITLE
 About “Service monitoring”

### ISSUE THREAD

**Issue by q158073378252010** [jrgp/linfo#63]
```
// Format: Label => path to executable or array containing arguments to be checked
$settings['services']['executables'] = array(
	// 'MySQLd' => '/usr/sbin/mysqld' // uncomment to enable
	// 'BuildSlave' => array('/usr/bin/python', // executable
	//						1 => '/usr/local/bin/buildslave') // argv[1]
);
```

![2017-08-15 01 49 07](https://user-images.githubusercontent.com/8859611/29284219-6174129c-815c-11e7-8ad3-513dd0a8c12c.png)
I want to get the red box service in Linfo.
Is it feasible? 
What should I do with the above configuration?

**Comment by jrgp** [comment]
what is redbox?

**Comment by q158073378252010** [comment]
@jrgp  I am sorry，
 Red frame
 Red frame
