### ISSUE TITLE
Class 'COM' not found

### ISSUE THREAD

**Issue by gemal** [jrgp/linfo#64]
Fatal error: Class 'COM' not found in linfo\src\Linfo\OS\Windows.php on line 52

using `# v.3.0.1 8/24/2016`

**Comment by jrgp** [comment]
You need to have PHP's COM extension installed for linfo to work on windows.

**Comment by jrgp** [comment]
I'm going to close this as installing COM should definitely fix this. Feel free to reopen/reply if it does not.
