### ISSUE TITLE
A request to amend a license for a fork.

### ISSUE THREAD

**Issue by Gemorroj** [jrgp/linfo#81]
https://github.com/Gemorroj/linfo/issues/8
https://github.com/jrgp/linfo/compare/master...Gemorroj:master

I have a fork of this library.
There have been many changes in the fork. I want to change the license to LGPL. As far as I know, I have to ask permission from the author of the original GPL code.

**Comment by jrgp** [comment]
I personally don't have a problem with Linfo (or a fork) being relicensed as LGPL. I should have made it MIT or BSD to begin with, but at the time all the cool kids were using GPL and that's what I went with.

The problem is I can't speak for all of Linfo's committers/contributors aside from me, as all of them would also have to approve the license change. This is the same problem that other open source projects face when they try to change licenses, afaik.

Aside from that, I think it'd be cool if some of your changes could be reflected back upstream. PRs always welcome.

**Comment by Gummibeer** [comment]
@jrgp how about creating a PR with license change and request review of all contributors - after some dass/weeks IT would be possible to see a full result or at least a trend.
I'm not deep into license but how I know Copyrights 100% of contributors have to accept I think?

**Comment by Gummibeer** [comment]
@Gemorroj I would also like to see some changes coming back - but a lot of your changes are "just" dropping support for OS/libs!?

**Comment by jrgp** [comment]
It would be kind of tricky to get approval from everyone as some of the commits were diffs people emailed me, back when this was SVN on sourceforge. 

I’m going to do some research and see what I can do.

**Comment by Gummibeer** [comment]
An Idea would be If there is a deadline possibility - so inform all (even SVN should have an e-mail?) and If there is no response in 30days it is an auto-accept. But no idea If something like this is applicable with current law?

**Comment by Gemorroj** [comment]
@jrgp, @Gummibeer Thank you for the detailed explanation.
So far, the main changes concern API. For example, the settings are completely removed. And also, more obvious structure of the given data ([Info.php](../../../Gemorroj/linfo/blob/master/src/Info.php)).

about license, I remember collecting consents to change the license for the phpexcel project. It seems that the license could not be changed. You can read the comments, if interesting. https://github.com/PHPOffice/PhpSpreadsheet/issues/140

**Comment by jrgp** [comment]
What I should have done is added a contributor license agreement (CLA) file saying that I have the right to change the license of contributions as I see fit, but I didn't know this was a thing at the time. At the time, I just cared about the quality of the code itself.

However, I looked at @Gemorroj's changes, and in my opinion, it largely counts as a rewrite as so much is stripped out and changed. I grant him permission to rename/relicense/refactor/etc those files as he sees fit, as they're his.

**Comment by jrgp** [comment]
Also, I don't really think copyleft restrictions of PHP code matters all that much, as when you distribute your app/library it's always going to be in source form. The only license which would cause problems is AGPL (you can do research as to why).

**Comment by jrgp** [comment]
I remember now that GPL/LGPL/copyleft can make it harder for corporations to use open source projects, whereas MIT/BSD/permission ones don't cause them problems.

I'll make a GH issue later asking all of our contributors for permission, and also manually email other people later. As there aren't a ton of contributors maybe I'll be able to get permission from everyone. I'm most concerned about translations, but maybe those files could stay GPL with others being moved to MIT.

Will follow up with this more later.

**Comment by jrgp** [comment]
Just made #82 we'll see what happens.

**Comment by jrgp** [comment]
It's now MIT.. Do whatever you like.
