### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED on windows

### ISSUE THREAD

**Issue by evazzadeh** [jrgp/linfo#89]
Hi
Its better to add some documentation about running on windows!

I have ERR_CONTENT_DECODING_FAILED error and after some search found that is because force gzip on linfo. 

By enable `zlib.output_compression` in `php.ini` its working. but maybe it's better to describe this or disable force gzip in request header.

**Comment by jrgp** [comment]
Probably would be a good idea to use init_get() or similar to evaluate the value of zlib.output_compression at runtime to decide whether to do ob_start with the ob_gzhandler method. Or maybe don't use ob_gzhandler at all and find some other way of doing it depending on what the client requests.

**Comment by Gummibeer** [comment]
For me, in my setups, nginx is responsible for gzip - and I don't see a reason why PHP should do this. It will/could lead to a double work cause nginx have to stay with this setting for css, js and image files.

**Comment by jrgp** [comment]
Should be fixed per https://github.com/jrgp/linfo/commit/a2c8662805333c4921b9b40d4d6c333b0a63fbea

Please confirm.

**Comment by evazzadeh** [comment]
yep;)
fixed, thanks.
