### ISSUE TITLE
Wrong Temperature Reported on CPU

### ISSUE THREAD

**Issue by zbczyvgy** [jrgp/linfo#96]
linfo improperly reports on 1 out of 4 cores for my Intel CPU.
My CPU is running mostly at ~30 degrees Celsius when idle, linfo, however, reports one of the cores being at ~45. And each time I load the page it is a different core. Gotta fix that.
![2018-08-06-005315_480x129_scrot](https://user-images.githubusercontent.com/23407361/43690484-5935ff4e-9913-11e8-8802-9e4796607a28.png)
![2018-08-06-005326_657x204_scrot](https://user-images.githubusercontent.com/23407361/43690485-5bee44da-9913-11e8-9487-dda52e21daee.png)

Which logs do you want to see?

**Comment by jrgp** [comment]
Sorry for delayed response, but Linfo reads these values from the same location in /sys that the `sensors` command reads from. Due to these values always fluctuating, the values will always be different.  If you still have questions feel free to reply.
