### ISSUE TITLE
AutoRefesh

### ISSUE THREAD

**Issue by emrecandan** [jrgp/linfo#99]
can you tell me were am i add autorefresh server cpu,memory ext. values with jquery timer?

**Comment by ikunyemingor** [comment]
Hi I've used like this with composer, php, js and html:
**PHP**
`
use Linfo\Linfo;
$info   = new Linfo();
$parser = $info->getParser();

$infoData = [
"cpuLoad"   => $parser->getLoad()
];
echo json_encode(["infoData" => $infoData]);
`

**HTML and JavaScript**
`
<html lang="en">
  <head>
    <title>Bootstrap 101 Template</title>
  </head>
  <body>
   <div id="cpu"></div>
    <script src="jquery.min.js"></script>
    <script>
        $(document).ready(function () {
       // Initial load to show server info.
        updateServerInfo();

       // Refresh server info every 5 seconds..
        setInterval(function () {
            updateServerInfo();
        }, 5000);

       function updateServerInfo() {
            $.ajax({
                    dataType: 'json',
                    type: "POST",
                    url: "/phpFile.php"
                }).done(function (_data) {
                    $('#cpu').html(_data.infoData.cpuLoad);
            }).fail(function (xhr) {
                var json = JSON.parse(xhr.responseText);
               console.error(json.error.text);
            });
        }
    });
</script>
  </body>
</html>
`

Hope this helps...

**Comment by jrgp** [comment]
^ That's a nice example on how to use Linfo as a library :) closing
